import type { BotIdentity } from "./types.ts";

type BotRegistryEntry = Readonly<BotIdentity & { pattern: RegExp }>;

export const BOT_REGISTRY: readonly BotRegistryEntry[] = [
  { pattern: /GPTBot/i, botId: "gptbot", botName: "GPTBot", vendor: "OpenAI", purpose: "training" },
  { pattern: /OAI-SearchBot/i, botId: "oai-searchbot", botName: "OAI-SearchBot", vendor: "OpenAI", purpose: "search_indexing" },
  { pattern: /ChatGPT-User/i, botId: "chatgpt-user", botName: "ChatGPT-User", vendor: "OpenAI", purpose: "realtime_citation" },
  { pattern: /OAI-AdsBot/i, botId: "oai-adsbot", botName: "OAI-AdsBot", vendor: "OpenAI", purpose: "other" },
  { pattern: /ClaudeBot/i, botId: "claudebot", botName: "ClaudeBot", vendor: "Anthropic", purpose: "training" },
  { pattern: /Claude-SearchBot/i, botId: "claude-searchbot", botName: "Claude-SearchBot", vendor: "Anthropic", purpose: "search_indexing" },
  { pattern: /Claude-User/i, botId: "claude-user", botName: "Claude-User", vendor: "Anthropic", purpose: "realtime_citation" },
  { pattern: /Claude-Web/i, botId: "claude-web", botName: "Claude-Web", vendor: "Anthropic", purpose: "realtime_citation" },
  { pattern: /anthropic-ai/i, botId: "anthropic-ai", botName: "anthropic-ai", vendor: "Anthropic", purpose: "training" },
  { pattern: /PerplexityBot/i, botId: "perplexitybot", botName: "PerplexityBot", vendor: "Perplexity", purpose: "search_indexing" },
  { pattern: /Perplexity-User/i, botId: "perplexity-user", botName: "Perplexity-User", vendor: "Perplexity", purpose: "realtime_citation" },
  { pattern: /Googlebot-Image/i, botId: "googlebot-image", botName: "Googlebot-Image", vendor: "Google", purpose: "search_indexing" },
  { pattern: /Googlebot-Video/i, botId: "googlebot-video", botName: "Googlebot-Video", vendor: "Google", purpose: "search_indexing" },
  { pattern: /Googlebot/i, botId: "googlebot", botName: "Googlebot", vendor: "Google", purpose: "search_indexing" },
  { pattern: /GoogleOther-Image/i, botId: "googleother-image", botName: "GoogleOther-Image", vendor: "Google", purpose: "search_indexing" },
  { pattern: /GoogleOther-Video/i, botId: "googleother-video", botName: "GoogleOther-Video", vendor: "Google", purpose: "search_indexing" },
  { pattern: /GoogleOther/i, botId: "googleother", botName: "GoogleOther", vendor: "Google", purpose: "search_indexing" },
  { pattern: /Google-Extended/i, botId: "google-extended", botName: "Google-Extended", vendor: "Google", purpose: "training" },
  { pattern: /Yeti/i, botId: "yeti", botName: "Yeti", vendor: "Naver", purpose: "search_indexing" },
  { pattern: /NaverBot/i, botId: "naverbot", botName: "NaverBot", vendor: "Naver", purpose: "search_indexing" },
  { pattern: /bingbot/i, botId: "bingbot", botName: "bingbot", vendor: "Microsoft", purpose: "search_indexing" },
  { pattern: /msnbot/i, botId: "msnbot", botName: "msnbot", vendor: "Microsoft", purpose: "search_indexing" },
  { pattern: /BingPreview/i, botId: "bingpreview", botName: "BingPreview", vendor: "Microsoft", purpose: "search_indexing" },
  { pattern: /MicrosoftPreview/i, botId: "microsoftpreview", botName: "MicrosoftPreview", vendor: "Microsoft", purpose: "search_indexing" },
  { pattern: /Applebot-Extended/i, botId: "applebot-extended", botName: "Applebot-Extended", vendor: "Apple", purpose: "training" },
  { pattern: /Applebot/i, botId: "applebot", botName: "Applebot", vendor: "Apple", purpose: "search_indexing" },
  { pattern: /DuckAssistBot/i, botId: "duckassistbot", botName: "DuckAssistBot", vendor: "DuckDuckGo", purpose: "realtime_citation" },
  { pattern: /DuckDuckBot/i, botId: "duckduckbot", botName: "DuckDuckBot", vendor: "DuckDuckGo", purpose: "search_indexing" },
  { pattern: /Amazonbot/i, botId: "amazonbot", botName: "Amazonbot", vendor: "Amazon", purpose: "training" },
  { pattern: /Amzn-SearchBot/i, botId: "amzn-searchbot", botName: "Amzn-SearchBot", vendor: "Amazon", purpose: "search_indexing" },
  { pattern: /Amzn-User/i, botId: "amzn-user", botName: "Amzn-User", vendor: "Amazon", purpose: "realtime_citation" },
  { pattern: /Meta-WebIndexer/i, botId: "meta-webindexer", botName: "Meta-WebIndexer", vendor: "Meta", purpose: "search_indexing" },
  { pattern: /Meta-ExternalFetcher/i, botId: "meta-externalfetcher", botName: "Meta-ExternalFetcher", vendor: "Meta", purpose: "realtime_citation" },
  { pattern: /Meta-ExternalAgent/i, botId: "meta-externalagent", botName: "Meta-ExternalAgent", vendor: "Meta", purpose: "training" },
  { pattern: /Meta-ExternalAds/i, botId: "meta-externalads", botName: "Meta-ExternalAds", vendor: "Meta", purpose: "other" },
  { pattern: /FacebookExternalHit/i, botId: "facebookexternalhit", botName: "FacebookExternalHit", vendor: "Meta", purpose: "other" },
  { pattern: /CCBot/i, botId: "ccbot", botName: "CCBot", vendor: "Common Crawl", purpose: "training" },
  { pattern: /Bytespider/i, botId: "bytespider", botName: "Bytespider", vendor: "ByteDance", purpose: "training" },
  { pattern: /YouBot/i, botId: "youbot", botName: "YouBot", vendor: "You.com", purpose: "search_indexing" },
  { pattern: /cohere-ai/i, botId: "cohere-ai", botName: "cohere-ai", vendor: "Cohere", purpose: "training" },
  { pattern: /MistralAI-User/i, botId: "mistralai-user", botName: "MistralAI-User", vendor: "Mistral AI", purpose: "realtime_citation" },
];
